services:
  # Core API with MongoDB
  api:
    extends:
      file: packages/core-api/docker-compose.yml
      service: api
    build:
      context: .
      dockerfile: packages/core-api/Dockerfile

  mongodb:
    extends:
      file: packages/core-api/docker-compose.yml
      service: mongodb

  # Future: Chat service

networks:
  staples-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
