services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - '3000:3000'
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/staples-checker
      - NODE_ENV=production
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_DATABASE=staples-checker
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
